# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BenchTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'JSONModel'
  pod 'AWSCognito'
  pod 'AWSDynamoDB'
  pod 'AWSS3'

  # Pods for BenchTracker

  target 'BenchTrackerTests' do
    inherit! :search_paths
  end

end
