platform :ios, '10.0'
inhibit_all_warnings!

target 'BenchTracker' do
  use_frameworks!

  pod 'JSONModel'
  pod 'ZFDragableModalTransition'
  pod 'HMSegmentedControl'
  pod 'FSCalendar'
  pod 'MGSwipeTableCell'
  pod 'MJExtension'
  pod 'MMQRCodeScanner'
  pod 'PNChart'
  pod 'XLForm'
  pod 'Appirater'
  pod 'Onboard'
  pod 'Toast'
  pod 'WZLBadge'
  pod 'AWSCognito'
  pod 'AWSDynamoDB'
  pod 'Crashlytics'
  pod 'Amplitude-iOS'

  target 'BenchTrackerTests' do
    inherit! :search_paths
  end

end
