# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BenchTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'JSONModel'
  pod 'ZFDragableModalTransition'
  pod 'HMSegmentedControl'
  pod 'FSCalendar'
  pod 'MGSwipeTableCell'
  pod 'MJExtension'
  pod 'MMQRCodeScanner'
  pod 'PNChart'
  pod 'XLForm'
  pod 'Appirater'
  pod 'Onboard'
  pod 'Toast'
  pod 'WZLBadge'

  # Pods for BenchTracker

  target 'BenchTrackerTests' do
    inherit! :search_paths
  end

end
